-- MySQL Script generated by MySQL Workbench
-- Tue Sep 28 22:15:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema citas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citas` DEFAULT CHARACTER SET utf8 ;
USE `citas` ;

-- -----------------------------------------------------
-- Table `citas`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`tutor` (
  `idtutor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idtutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `hora` VARCHAR(45) NULL,
  `idtutor` INT NULL,
  `idcliente` INT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_tutor_curso_idx` (`idtutor` ASC),
  INDEX `fk_cliente_curso_idx` (`idcliente` ASC),
  CONSTRAINT `fk_tutor_curso`
    FOREIGN KEY (`idtutor`)
    REFERENCES `citas`.`tutor` (`idtutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_curso`
    FOREIGN KEY (`idcliente`)
    REFERENCES `citas`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas`.`lider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`lider` (
  `idlider` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contraseña` VARCHAR(100) NULL,
  PRIMARY KEY (`idlider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citas`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`participante` (
  `idparticipante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `idempresa` INT NULL,
  PRIMARY KEY (`idparticipante`),
  INDEX `fk_empresa_participante_idx` (`idempresa` ASC),
  CONSTRAINT `fk_empresa_participante`
    FOREIGN KEY (`idempresa`)
    REFERENCES `citas`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
